### ISSUE TITLE
Errors on npm install

### ISSUE THREAD

**Issue by ddellostritto** [litdevelopers/tinder#16]
Hi!

Getting these errors on `npm install`:
```
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint@^3.3.1 but none was installed.
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.
npm WARN react-addons-shallow-compare@15.4.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN react-addons-test-utils@15.4.2 requires a peer of react-dom@^15.4.2 but none was installed.
npm WARN scroll-behavior@0.7.0 requires a peer of history@^1.12.1 || ^2.0.0 but none was installed.
```

Any help appreciated!

**Comment by paulxuca** [comment]
It seems that it's missing a few packages in ```package.json```!

Try installing:
```
eslint
eslint-plugin-import
webpack
react
react-dom
history
```

If that doesnt work, let me know! I can update the package.json to prevent this in the future.

**Comment by ddellostritto** [comment]
Thanks for the help! Though tried those, I'm still getting the same error as before; when I tried running the lines you gave me, I got the following (perhaps I have to cd?)

```
-bash: eslint: command not found
-bash: eslint-plugin-import: command not found
-bash: webpack: command not found
-bash: react: command not found
-bash: react-dom: command not found
```
Searching around I [found this](http://stackoverflow.com/questions/36862546/eslint-error-install-from-command-line) and tried:
`sudo npm install -g ...`

With each (not an expert in terminal here, appreciate the help!).

Could you please give me any suggestions?

**Comment by paulxuca** [comment]
Yeah! It seems that you arent in the folder or you forgot to type ```npm install``` before installing the package. So it should be ```npm install react (and all the other packages)```

**Comment by ddellostritto** [comment]
Hi!

Still getting these messages
```
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint@^3.3.1 but none was installed.
npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.
npm WARN react-addons-shallow-compare@15.4.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN react-addons-test-utils@15.4.2 requires a peer of react-dom@^15.4.2 but none was installed.
npm WARN scroll-behavior@0.7.0 requires a peer of history@^1.12.1 || ^2.0.0 but none was installed.
```

I've tried a generic `npm install ...` as well as `npm install eslint@^3.3.1` for example, thinking that it was a version issue. 

Process: 
- download the zip
- unzip
- open terminal, cd into the directory (`open .` to make sure I'm in the right directory)
- ran generic `npm install ...` followed by `npm install`, get the messages above
- ran specific `npm install eslint@^3.3.1` (for example) followed by `npm install`, get the messages above

What am I doing wrong? 

Thanks again for the help...

**Comment by eddiewang** [comment]
Try nuking the project locally, and clone it again. Make sure you run "npm install" within the folder of where you cloned the code. What version of node and npm are you using?

**Comment by ddellostritto** [comment]
npm = 4.1.1
node = 6.9.4

I'll download the files again, delete the directory and go through the steps.

**Comment by eddiewang** [comment]
hold on - i'm going to try setting up yarn for you, that might solve the dependency problems.

**Comment by eddiewang** [comment]
try now @ddellostritto - install yarn via brew if you don't already have it, and then just do "yarn" in the cmd line of the current working dictionary.

**Comment by ddellostritto** [comment]
Recently installed homebrew, typed in yarn, it's doing its thing, I'll update in a few

**Comment by paulxuca** [comment]
hey @ddellostritto!

I just installed a fresh copy of the app and those warnings can be ignored. The app runs fine regardless! :)

**Comment by ddellostritto** [comment]
alright, going to try again following from the instructions

**Comment by paulxuca** [comment]
hurray! Let us know how it goes! 👍

**Comment by ddellostritto** [comment]
thanks!! @paulxuca got it up and running, fyi, conflicts with flamite for chrome (it redirects to their extension). I'll have to see if the whole "see who already likes you" bit is true when I can swipe again.
