### ISSUE TITLE
How can I figure out who liked me?

### ISSUE THREAD

**Issue by GrandmasterMeio** [litdevelopers/tinder#17]
Hi! Great app you have here, congrats sir!
The readme tells me that I can figure out who liked me, but I can't find nothing like that in the app itself...
I'm doing something wrong? Can you let me know what can I do to figure out?

Thanks

**Comment by paulxuca** [comment]
If we can figure out the data (the data provided to us from **tinder**), it'll be a red border around a recommendation card. It's automatic and doesnt require any additional steps!

**Comment by GrandmasterMeio** [comment]
Very good, Paulxuca. Would be a nice idea add this information at the Readme? 
Congrats and thanks for your work at discovering the new access token!

**Comment by paulxuca** [comment]
Thanks and hope you get it to work for you! :)
