### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by fedecupe** [litdevelopers/tinder#19]
attached log (fresh install of npm, fresh git clone)
[npm-debug.log.txt](https://github.com/litdevelopers/tinder/files/801613/npm-debug.log.txt)

**Comment by shellbotx** [comment]
Hey, we're currently working on this issue over here:
#18 

Unless I'm mistaken your problem is the same as ours and involves an issue in building the dependencies.

**Comment by eddiewang** [comment]
try now! and pls refer to #18 thank you!
