### ISSUE TITLE
Can you please make a video tutorial?

### ISSUE THREAD

**Issue by sillasgonzaga** [litdevelopers/tinder#21]
I"m not sure of what step 3 means:

_Open chrome and load in a new "unpacked extension" from the extensions screen._

**Comment by henriquelbsouza** [comment]
I don't think there is need for a video tutorial... Really quick explanation on that:

1- Go to the vertical dots at the top right corner
2- Settings (it will open a new tab with chrome settings)
3- At top left corner there is "Extensions" click on it.
4- At the top again there is a button labeled "Load unpacked extension"
5- Click and go to SRC as explained in the README file....

That is it...
