### ISSUE TITLE
Last active inaccuracy

### ISSUE THREAD

**Issue by frankkkiiie** [litdevelopers/tinder#25]
Have noticed that I got messages from matches in realtime and their status still says active "xx" hours ago.

**Comment by eddiewang** [comment]
Thanks, I've noticed it was inaccurate as well. May be the date parser in utils. I don't have time fix minor bugs atm as I'm busy with other projects. Pull reqs welcome.

**Comment by khecha** [comment]
For me it says "last active 857 days ago" for all my matches. Is this a known issue?

**Comment by eddiewang** [comment]
@khecha @frankkkiiie the api no longer displays last active and all data is wiped to show a 2014 date.

**Comment by eddiewang** [comment]
If someone could remove the date from the profile cards that'd be great.

**Comment by jdunk** [comment]
PR: https://github.com/litdevelopers/tinder/pull/30
