### ISSUE TITLE
Filter by 'Common Connections'

### ISSUE THREAD

**Issue by cellininicholas** [litdevelopers/tinder#26]
It would be cool if I could add a number of Facebook Friends to a filter, and you could select 'Any' or 'All' then it would only show matches with ANY of the friends you mentioned in common or ALL of the friends you mentioned in common.

If you like the personality of one friend in particular, you may also like their friends.

Just a thought/idea.

**Comment by eddiewang** [comment]
Great idea, we have this feature implemented in a private version of the new app, but we disabled the liking common friends after testing the feature out, bc you can get ghost-banned pretty fast if you like people from different locations.
