### ISSUE TITLE
Photo sizes

### ISSUE THREAD

**Issue by 4DeepThought2** [litdevelopers/tinder#28]
Does anyone have any idea how to make it so that photos aren't zoomed in so far on the matches page?  I see the css here:

![image](https://cloud.githubusercontent.com/assets/13695270/26001485/25f21c78-36f2-11e7-84f4-89ec33a9639f.png)

But I dont see that element in any of the css files.  I suck at CSS btw.   How can I make it so that the photos aren't zoomed in and we can see the entire picture?

**Comment by paulxuca** [comment]
Hey 4DeepThought2! :) 

Thanks for reaching out! 

To change the size of the background image:
Go to: https://github.com/litdevelopers/tinder/blob/master/app/components/DetailView/index.js#L73
And change `backgroundSize: 'cover' => backgroundSize: 'contain'`.

Let us know if that works :)

**Comment by eddiewang** [comment]
There's also a different version of the app (very similar, just a different UI) with the photos zoomed out. You can download the chrome extension here: https://github.com/eddiewang/lit-extension @4DeepThought2

**Comment by 4DeepThought2** [comment]
@eddiewang - Cant seem to get that version to work.  Any special instructions?

**Comment by eddiewang** [comment]
@4DeepThought2 sorry i stopped hosting that version recently.
