### ISSUE TITLE
Recommendations list is empty

### ISSUE THREAD

**Issue by SergeyYu** [litdevelopers/tinder#29]
Hi, In the web gui my recommendations list is empty, while other tabs are OK. I even can change the distance and age in web and then see it's applied in my tablet app. On the tablet recommendations are OK and I can swipe successfully. 
Any possibility to debug it?

**Comment by SergeyYu** [comment]
It looks like the data is transferred but isn't displayed

![screenshot from 2017-05-13 20-22-54](https://cloud.githubusercontent.com/assets/28674420/26027653/3fe8c464-381a-11e7-9687-101a3f58a937.png)

**Comment by eddiewang** [comment]
Try the updated version. You can download the chrome extension here: https://github.com/eddiewang/lit-extension

**Comment by eddiewang** [comment]
Actually, this is still an issue - if anyone can debug this i'll keep the issue open.

**Comment by SergeyYu** [comment]
Do you mean to use your extension instead of previous one? Just after enabling it in the Chrome it redirects to http://lit.eddiewang.me/browse. Is it normal (btw, it stuck on "Preparing faces"...)? Any additional settings need to be done? Thanks~

**Comment by eddiewang** [comment]
no configuration needed. it's hosted which is why there's a URL. just click it and press login - if you have a facebook account it should automatically work... unless Tinder changed their API and both apps are now broken...

**Comment by SergeyYu** [comment]
Unfortunately I get this 
![screenshot from 2017-05-13 21-58-52](https://cloud.githubusercontent.com/assets/28674420/26028356/7140c3b0-3827-11e7-81bf-044e90a27363.png)

**Comment by eddiewang** [comment]
@SergeyYu clear your cache, login to Facebook first, and try again.
Also - make sure your Facebook has a Tinder account associated with it setup (you need to download Tinder on your phone and sign in at least once).

If all those steps don't work, it might be an api issue. I'll look into this when i have more time. Lmk.

**Comment by SergeyYu** [comment]
After all these steps when start extension it asks to press login button but then immediately switches to "Preparing Faces".

**Comment by SergeyYu** [comment]
returning to the localhost version - this the console log I get when go to the recommendation tab
![screenshot from 2017-05-13 23-28-58](https://cloud.githubusercontent.com/assets/28674420/26029018/fe69c5c8-3833-11e7-97e7-076999243259.png)

**Comment by eddiewang** [comment]
I haven't found any problems with the app after debugging it. are you sure it's not a firewall issue?

**Comment by SergeyYu** [comment]
well, it should not affect it
$ sudo ufw status
Status: inactive

None of other are installed.

**Comment by SergeyYu** [comment]
Now I found that info message that can't connect to server is displayed when open recommendations tab
![screenshot from 2017-05-28 22-47-18](https://cloud.githubusercontent.com/assets/28674420/26531719/e4b94106-43f7-11e7-88bd-8d6f2f0d8186.png)

**Comment by SergeyYu** [comment]
is it possible to debug local version to check if it handles received data correctly and what part of the app doesn't display it? Im not a programmer, but suppose that local js should display data on this tab page. Maybe smth goes wrong with it? I can perform some steps if you share them...

**Comment by eddiewang** [comment]
hmm. have you tried installing it on another PC. I have a feeling it's not the app's problem bc I verified the api still works. The server is localhost - it opens a port locally and the api calls are performed there.

**Comment by SergeyYu** [comment]
Which operation system do you suggest to use for checking on another PC?

**Comment by eddiewang** [comment]
Windows and OSX would be fine, but I use OSX

**Comment by jimmyhsu** [comment]
I found this repo after digging through the API to scrape for a dataset – it appears Tinder does indeed rate limit you and soft ban you for the day for requesting for too many people.

Check the response when pinging for recs, you might get this as a response:
`{'message': 'recs limited', 'status': 200}`

**Comment by eddiewang** [comment]
yep - the soft ban isn't lifted by our app, but our app shouldn't ban you, it fetches just a few times on load.

**Comment by jdunk** [comment]
I experienced this issue also. It happens when any of your prospective matches don't have a `bio` property, which breaks thusly (as @SergeyYu's screenshot shows) :

```
uncaught at matchesSaga 
 at dataLoadLocalWatcher 
 at loadLocalData 
 at fetchRecommendationsAction 
 TypeError: Cannot read property 'trim' of undefined
```
...because of this line right here:
https://github.com/litdevelopers/tinder/blob/91a0f7879c3ce89039e3492ca78888deed3cffbe/app/components/MatchCard/index.js#L14
