### ISSUE TITLE
Problem with webpack 2.1

### ISSUE THREAD

**Issue by fmdelvalle** [litdevelopers/tinder#35]
FYI, 

The package does not compile as it does not find webpack 2.1. Found the solution: you have to add "webpack-dev-server": "^1.14.1" to the package.json dependencies area.

Cheers,

Fernando

**Comment by fmdelvalle** [comment]
Also had to add more dependencies, as it was failing with JPEGs and PNGs on first access. Possibly there are some that aren't really needed:

    "pngquant-bin": "0.1.6",
    "gifsicle": "0.1.4",
    "jpegtran-bin": "0.2.3",
    "optipng-bin": "0.3.1",
    "pngquant-bin": "0.1.6",
    "grunt-contrib-imagemin": "0.3.0"

**Comment by fmdelvalle** [comment]
BTW, now it is working, and it seems awesome!

**Comment by eddiewang** [comment]
@fmdelvalle can you make a pull request with the fixes?
